# Generated by Django 4.2.1 on 2023-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yizhan', '0005_yizhan_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mulyizhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NA_zh', models.TextField(null=True, verbose_name='Answer_zh')),
                ('NQ_zh', models.TextField(null=True, verbose_name='Question_zh')),
                ('NA_en', models.TextField(null=True, verbose_name='Answer_en')),
                ('NQ_en', models.TextField(null=True, verbose_name='Question_en')),
                ('NA_ru', models.TextField(null=True, verbose_name='Answer_ru')),
                ('NQ_ru', models.TextField(null=True, verbose_name='Question_ru')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mulyizhan',
                'db_table': 'Mulyizhan',
            },
        ),
    ]
